image: registry.znuny.com/znuny/internal/alpine-deployment:stable

stages:
  - build
  - deploy

default:
  before_script:
    - pip3 install sphinx-book-theme
    - pip3 install sphinx-copybutton
    - pip3 install sphinxcontrib-mermaid
    - pip3 install sphinx-code-tabs
    - pip3 install sphinx-fontawesome

build:
  stage: build
  artifacts:
    paths:
      - build/
    expire_in: 48 hrs
  except:
    - merge_requests
  script:
    - make linkcheck SPHINXBUILD=sphinx-build
    - make html SPHINXBUILD=sphinx-build

deploy-znuny:
  stage: deploy
  only: 
    - znuny
  except:
    - merge_requests
  script:
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | ssh-add -
    - ssh-keyscan $DEPLOY_HOST  >> $HOME/.ssh/known_hosts
    - rsync -avz --delete ./build/html/* $DEPLOY_USER@$DEPLOY_HOST:/var/www/html/doc/znuny

github-sync:
  stage: deploy
  only: 
    - znuny
  except:
    - merge_requests
  script:
    - /usr/bin/sync_repo.sh git@github.com:znuny/manual.git

