image: registry.znuny.com/znuny/internal/alpine-deployment:stable

stages:
  - build
  - deploy

default:
  before_script:
    - pip3 install -r requirements.txt

build:
  stage: build
  image: python:bookworm
  artifacts:
    paths:
      - build/
    expire_in: 48 hrs
  except:
    - merge_requests
  script:
    - make linkcheck SPHINXBUILD=sphinx-build
    - make html SPHINXBUILD=sphinx-build

deploy-znuny:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^znuny-(lts_)?\d_\d/ && $CI_PIPELINE_SOURCE != "merge_request_event"
  script:
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | ssh-add -
    - ssh-keyscan $DEPLOY_HOST  >> $HOME/.ssh/known_hosts
    - rsync -avz --delete ./build/html/ $DEPLOY_USER@$DEPLOY_HOST:/var/www/html/doc/$CI_COMMIT_BRANCH

github-sync:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^znuny-(lts_)?\d_\d/ && $CI_PIPELINE_SOURCE != "merge_request_event"
  script:
    - /usr/bin/sync_repo.sh git@github.com:znuny/manual.git
